### ISSUE TITLE
[BUG]上传大文件会撑爆内存

### ISSUE THREAD

**Issue by johnlabor** [ww9592447/115Client#1]
没有仔细看代码，但一旦上传巨大文件，比如30G的文件啊，内存立刻上升至100%然后电脑就卡住了。
我内存是16G不够用。
谢谢。

**Comment by ww9592447** [comment]
> 沒有仔細看，但有上傳巨大的文件，30G的文件啊，內存上升到100%然後電腦就卡住了。我的內存是 謝謝 16G ，就像代碼一樣。

我手頭上沒有這麼大的文件能夠測試...
你  上最大同時上傳數  單文件上傳線程 
是設定多少
調低一點試試?

**Comment by ww9592447** [comment]
> 沒有仔細看，但有上傳巨大的文件，30G的文件啊，內存上升到100%然後電腦就卡住了。我的內存是 謝謝 16G ，就像代碼一樣。

已更新了 你更新下task文件夾下面的 upload.py即可

**Comment by johnlabor** [comment]
感谢，周末再测测看，先关issue。
