### ISSUE TITLE
浏览器获取的Cookie是一堆键值对，怎么填到.ini里的cookie=后面

### ISSUE THREAD

**Issue by zengruzhen** [ww9592447/115Client#2]

**Comment by ww9592447** [comment]
> _沒有提供說明。_

![未命名](https://user-images.githubusercontent.com/53929496/210162081-97e7fcbf-6be5-4c52-b117-53ebf8a15ac9.png)

整行複製進去即可
還有建議你重新下載最新的1.3版本  1.2版本 下載功能有點小BUG

**Comment by zengruzhen** [comment]
怪不得，我看的是这里
![image](https://user-images.githubusercontent.com/18514089/210169089-0b40fa5c-fb1f-448e-9ad5-60a28e296465.png)
