### ISSUE TITLE
上传的时候点击暂停或取消会闪退

### ISSUE THREAD

**Issue by 362227** [ww9592447/115Client#4]
上传的时候点击暂停或取消会闪退

**Comment by 362227** [comment]
File "D:\115Client-main\115Client-main\module.py", line 391, in allclose
    qtext.set_closes.left_click.emit(qtext)
AttributeError: 'MyIco' object has no attribute 'left_click'

**Comment by ww9592447** [comment]
> 文件“D:\115Client-main\115Client-main\module.py”，第 391 行，在 allclose qtext.set_closes.left_click.emit(qtext) AttributeError: 'MyIco' 對像沒有屬性 'left_click'

1.4.2 已修復
